version: '3.9'
services:
  server:
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
      - ${SOCKET_PORT}:${SOCKET_PORT}
  db:
    container_name: baucua_db
    image: mongo:4.4.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - baucua/:/data/db
  redis:
    image: redis:6.0-alpine
    container_name: baucua_redis
    ports:
      - '6379:6379'
volumes:
  baucua:
