version: '3.9'

services:
  server:
    container_name: baucua_server_prod
    image: baucua_server_prod:latest
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
      args:
        PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
        PM2_SECRET_KEY: ${PM2_SECRET_KEY}
